# Generated by Django 5.2.8 on 2025-11-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourseapp', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='final_exam_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='final_exam_score',
            field=models.FloatField(default=0),
        ),
    ]
