# Generated by Django 5.2.8 on 2025-11-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourseapp', '0003_enrollment_final_exam_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
