# Generated by Django 5.2.8 on 2025-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourseapp', '0004_enrollment_payment_status_enrollment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_id_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
