# Generated by Django 5.2.8 on 2025-11-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourseapp', '0006_coursepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='trusted_devices',
            field=models.JSONField(default=list),
        ),
    ]
